### PR TITLE
Add dependent sum datatype `Sigma` to saw-core prelude.

### PR DESCRIPTION
**Pull request by brianhuffman**

### CODE REVIEW

**Comment by eddywestbrook** [comment]
Looks good to me.

The only thing I can think to add would be to translate `Sigma` to the `sigT` type in Coq. (This definition of `Sigma` is predicative, so `sigT` is the particular sigma type in the Coq standard library that corresponds to predicative sigmas.) But this could also be something we do in the future...

**Comment by brianhuffman** [comment]
Oh right, I didn't think about how `saw-core-coq` is in this repo now, so we can also bundle `saw-core-coq` changes in the same PR. We should probably do that.

**Comment by brianhuffman** [comment]
It looks like the `SpecialTreatment` module already binds these names to the appropriate constants from the Coq standard library:
https://github.com/GaloisInc/saw-core/blob/26a21f3c7d99bb53461d407f383dec3a344e2f7f/saw-core-coq/src/Verifier/SAW/Translation/Coq/SpecialTreatment.hs#L432-L439

If these look right, then maybe that's all we need?

**Review by eddywestbrook — APPROVED** [review]
Yep, this is already done. How convenient!

**Pull request merged**
