### PR TITLE
Adapt to GaloisInc/cryptol#1128 "persistent-solver2".

### PR DESCRIPTION
**Pull request by brianhuffman**

### CODE REVIEW

**Comment by brianhuffman** [comment]
The removal of `meSolverConfig` will require changes to the `saw-script` package as well.

**Comment by robdockins** [comment]
This seems OK to me.  Although, there is an alternate design we could consider: should the solver instance just be stored in the `CryptolEnv`?  That would persist it for much longer, and may be what you want to do eventually anyway, as it will spawn solvers less often.

**Review by robdockins — APPROVED** [review]

**Comment by brianhuffman** [comment]
I'll open a ticket suggesting to store the solver instance in the `CryptolEnv`. This PR is intended to preserve the existing behavior as much as possible, and we can add solver persistence later (perhaps after we figure out all the issues related to restarting solvers after Ctrl-C).

**Comment by brianhuffman** [comment]
Instead of opening a new saw-core ticket, I just added some notes to GaloisInc/saw-script#953, which is already asking for this exact feature.

**Pull request merged**
