### PR TITLE
Speed up matching implementation used by `rewriteSharedTerm`

### PR DESCRIPTION
**Pull request by brianhuffman**
To check convertibility of expressions of type `Nat`, use a more efficient custom function instead of doing a bottom-up traversal with natConversions.

### CODE REVIEW

**Comment by atomb** [comment]
This PR currently includes both the `Integer` to `Natural` changes and the improvements to the matching code. I expect that if we do a normal merge of #46 and then, after that, merge this one, we'll still get a clean history, though.

**Comment by brianhuffman** [comment]
I expect this situation will arise quite frequently whenever I'm working on fixing performance bottlenecks: I may come up with multiple otherwise-unrelated changesets that I want to chain together for testing purposes, but they don't really seem to fit together for PR review purposes. But I guess github smooshes all the diffs together for the later ones anyway. I suppose in the future it would be better to just combine these kinds of things into a single PR.

**Comment by atomb** [comment]
If it turns out that you want to merge changes in the same order that you make them in the branch, it looks as though things work out nicely. Now that #46 is merged, the diff for #47 is smaller and more targeted. So keeping a long-running branch and making multiple pull requests seems workable, unless you want to merge them out-of-order.

**Comment by brianhuffman** [comment]
Well the diff is smaller now because I rebased this branch after merging the other one :)

Probably in the future I won't try to make so many pull requests in rapid succession.

**Pull request merged**
