### PR TITLE
Check types in context of private symbols

### PR DESCRIPTION
**Pull request by atomb**
Include both public and private symbols from imported modules when type checking. This addresses saw-script#971.

@brianhuffman, do you think this would have any undesirable side effects?

### CODE REVIEW

**Comment by brianhuffman** [comment]
The only real risk I can think of is that importing more names could possibly cause name clashes. But this can always be worked around with either explicit import lists or qualified imports, both of which are supported by the `CryptolEnv` API, so I think it's good.

I wasn't sure until I checked in `SAWScript/Parser.y` just now, but it appears that we actually do support both qualified imports and explicit import lists in the saw-script `import` command. I don't think I've ever seen any example saw-script files that use that feature, so we should probably add one to the examples or test suite.

**Comment by brianhuffman** [comment]
There are some alternative designs that we might want to consider.

One would be to let users of the `CryptolEnv` API choose whether or not to import private declarations from the imported module. You could implement this by replacing the `CryptolEnv` field `eImports :: [P.Import]` with the type `[(Bool, P.Import)]` (or something isomorphic to that).
https://github.com/GaloisInc/saw-core/blob/943f03ce02c72c834d7c0b14a9d4476125cf433e/cryptol-saw-core/src/Verifier/SAW/CryptolEnv.hs#L108-L109
The extra bit would indicate whether to do a "public only" or "public+private" import. Then the decision about whether or when to import private names would fall on the the program that uses `cryptol-saw-core` (i.e. saw-script). Such a type change in the `CryptolEnv` API would require patching saw-script, and then we'd still have to decide what behavior we want to implement on the saw-script side. We could default to the same behavior you've chosen here (i.e. always import private) but the benefit would be that further changes could be made without further modification of `cryptol-saw-core`.

Another option would be keep the API the same, but do the default behavior differently: Instead of *always* importing all the private names, we could make it import private names *only for qualified imports*. This would make it so that name clashes are never a problem, and it would still let saw-script users have access to private declarations if they want them.

**Review by brianhuffman — APPROVED** [review]
This seems fine. I'll let you decide whether you want to consider any of the alternative designs I suggested.

**Comment by atomb** [comment]
On further reflection, I do think that it would be valuable to give clients the ability to control which symbols are visible. Although the use cases I'm aware of right now would all benefit from access to private symbols, I could imagine future use cases where that was not true. So I'm inclined to adapt it to your suggested approach of including a flag in the `eImports` field. I have about doing that, though. That brings up one question, though: what should `initCryptolEnv` do?

https://github.com/GaloisInc/saw-core/blob/943f03ce02c72c834d7c0b14a9d4476125cf433e/cryptol-saw-core/src/Verifier/SAW/CryptolEnv.hs#L198-L200

Looking at that further, though, neither of those modules have any private symbols, so it doesn't really matte.r

**Review by brianhuffman — APPROVED** [review]
Looks good.

**Pull request merged**
