### PR TITLE
Move RME library to its own `rme` package.

### PR DESCRIPTION
**Pull request by brianhuffman**

### CODE REVIEW

**Comment by brianhuffman** [comment]
This is probably a good time for bikeshedding the `Data.RME` API. I'm pretty happy with `Data.RME.Base`, but there's a lot of different ways we could change `Data.RME.Vector`. Should we use the `Data.Vector` type in the API, or `[RME]`? Which endianness should we use? Should we provide an abstract datatype for vectors of `RME` formulas? What should functions do with arguments that are different bit-widths? What names should we choose for everything?

**Comment by robdockins** [comment]
I think we should make vectors of RME values abstract, so we can change the representation later if we like.  The choice of endianess is then an implementation detail.  I think the interface should be similar to the one for `What4.SWord`, so it is an error to pass vectors of different lengths, and we should provide very explicit `BE` and `LE` versions of packing, unpacking, testing bits and so on.

If we are going to use `Vector` for this, we should be very careful to use it in a way that minimizes copying; otherwise we should probably use a more forgiving datastructure like `Sequence`.

We definitely need more documentation explaining what the normal form is and what the invariants are.  @brianhuffman explained it to me some time ago, but I can't reconstruct that understanding from the code and documentation here.

**Comment by brianhuffman** [comment]
The datatype invariants are given in a comment next to the definition: https://github.com/GaloisInc/saw-core/blob/507f5deb316e659796ce8a463dc94d903f0f83e7/rme/src/Data/RME/Base.hs#L27-L32

As for explaining how the representation works and what the constructors mean, I suppose I could document that better. The `eval` function is really an executable specification of the semantics, but I should point that out explicitly. Perhaps a link to the Wikipedia page on Algebraic Normal Form and/or Reed-Muller Expansion would be nice to put in the module header.

I like the idea of using an abstract type for `RME` bitvectors, and keeping `Vector` out of the API completely. But that means that we'll have to add quite a few new functions, such as bitwise logical operators, shift/rotate, selection, concatenation, indexing, etc.

**Comment by brianhuffman** [comment]
I think maybe redoing the RME library API can be done in a separate PR, as those changes are orthogonal to whether or not the RME library is in a separate package. I'll open a separate ticket for making the API changes that we discussed here. I'll definitely make sure we clean up the API before publishing the `rme` library on hackage.

**Pull request merged**
