### PR TITLE
Saw what4 refactor

### PR DESCRIPTION
**Pull request by robdockins**
Begin refactoring the SAW<->What4 connection.  This PR moves translation code from `crucible-saw` into this package, where it more naturally belongs, and also cleans up some coding conventions in the What4 evaluator.

### CODE REVIEW

**Comment by robdockins** [comment]
Prerequisite for https://github.com/GaloisInc/saw-script/pull/997

**Review by brianhuffman — APPROVED** [review]
Looks good!

**Comment by brianhuffman** [comment]
It looks like the merge conflict is just due to a `String`/`FieldName` change, which will be trivial to fix.

**Comment by robdockins** [comment]
@brianhuffman, I think the merge conflict is fixed now.  I don't know if the CI failures are something to be concerned about.

**Comment by brianhuffman** [comment]
No, the CI tests are only for saw-core-coq, and they are still in the experimental stage; you don't need to pay attention to those.

**Pull request merged**
